<script type="text/javascript" src="<?php echo $this->getAbsoluteUrl(); ?>js/lib/prototype.js"></script>
<script type="text/javascript" src="<?php echo $this->getAbsoluteUrl(); ?>js/lib/md5-min.js"></script>
<script type="text/javascript" src="<?php echo $this->getAbsoluteUrl(); ?>js/app.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getAbsoluteUrl(); ?>css/adminpanel.css">