<div class="login-form-wrapper">
    <form id='login-form' action="<?php echo $this->getBaseUrl(); ?>admin/index/authorize" method="post">
        <h1>Log in into Adminpanel</h1>
        <div class="login-form">
            <div class="username">
                <span>Username</span>
                <input type="text" name="user">
            </div>
            <div class="password">
                <span>Password</span>
                <input type="password">
                <input type="hidden" name="pass">
            </div>
            <div class="actions">
                <input id="submit-form" type="submit" value="Log in">
            </div>
        </div>
    </form>
</div>
