<?php
/**
 * Copyright <c>  Artur Paklin
 * paklin.artur@gmail.com
 */
?>
<?php
    $postsArray = array();
    $postsArray = getPostsByDiapazone(0, 20);
    $postsLen = count($postsArray);
?>
<div class="posts">
    <table class="data-table">
        <tr class="head-col">
            <td class="col">ID</td>
            <td class="col">Title</td>
            <td class="col">Content(100)</td>
            <td class="col">Date</td>
        </tr>
        <?php
            $i = 0;
            while($i < $postsLen) {
                echo "<tr>";
                echo "<td><p>" . $postsArray[$i]->getRecID() . "</p></td>";
                echo "<td><p>" . $postsArray[$i]->getTitle() . "</p></td>";
                echo "<td><p>" . substr($postsArray[$i]->getContent(), 0, 100) . "</p></td>";
                echo "<td><p>" . $postsArray[$i]->getDate() . "</p></td>";
                echo "<td><button type='submit'>Edit</button></td>";
                echo "</tr>";
                $i++;
            }
        ?>
    </table>
</div>