<html>
	<head>
        <?php echo $this->renderBlock('header_includes'); ?>
	</head>

	<body>
		<div class="wrapper">
			<div class="header">
                <?php echo $this->renderBlock('header');?>
            </div>
            <div class="body">
                <?php echo $this->renderBlock('banner'); ?>
                <?php echo $this->renderBlock('posts'); ?>
            </div>
            <div class="footer">
                <?php echo $this->renderBlock('footer'); ?>
            </div>
		</div>
	</body>
</html>