<h1>Posts</h1>
<!-- This code part Must be deleted, only for sample data -->
<?php $posts = $this->getPostsCollection(); ?>
<div class="posts-body">
    <?php foreach($posts as $post): ?>
        <div class="post">
            <div class="title">
                <span><?php echo $post['title']; ?></span>
            </div>
            <div class="content">
                <p> <?php echo $post['content']; ?></p>
            </div>
            <div class="content-data">
                <span class="author"><?php echo $post['author']; ?></span>
                <span class="date"><?php echo $post['published_date']; ?></span>
            </div>
            <div class="actions">
                <a href="<?php echo '#'; ?>" post-id="<?php echo $post['id']; ?>">
                    <div class="view-button">
                        <span>View</span>
                    </div>
                </a>
            </div>
        </div>
    <?php endforeach; ?>

</div>
