<div class="posts block">
    <h1>Posts</h1>
    <?php $posts = $this->getPostsCollection(); ?>
    <div class="ui items posts">
        <?php foreach($posts as $post): ?>
            <div class="item">
                <div class="ui small image">

                </div>
            
            <div class="middle aligned content">
                <div class="header">
                    <?php echo $post['title']; ?>
                </div>
                <div class="description">
                    <p><?php echo $post['content']; ?></p>
                </div>
                <div class="extra">
                <a href="<?php echo '#'; ?>" post-id="<?php echo $post['id']; ?>">
                    <div class="ui right floated button">
                    View
                    </div>
                </a>   
                </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>