<html>
    <head>
        <?php echo $this->renderBlock('admin_header_includes'); ?>
    </head>
    <body class="adminpanel">
        <div class="wrapper">
            <div class="nav-menu">
                <ul class="navigation">
                    <li class="item">
                        <span>Users</span>
                        <ul class="submenu leve1">
                            <li class="item">View Users</li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="content">
<!--                --><?php //$this->getContent(); ?>
            </div>
        </div>
    </body>
</html>